version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/packaging-delivery-service-777-task-definition:latest"
        LoadBalancerInfo:
          ContainerName: "packaging-delivery-service-777"
          ContainerPort: "5000"
        PlatformVersion: "LATEST"